### ISSUE TITLE
Visible pricing for events and student discount

### ISSUE THREAD

**Issue by rowan01g** [rowan01g/boardwalk-games#6]
**User Story**
As a Student Gamer, I want to find clear information about upcoming events, pricing and student discounts, so I can plan my visit within my budget and time constraints.
**Acceptance Criteria**

- [ ] Clear and accurate pricing information for events is displayed and easy to find
- [ ] Student discount information stands out near pricing information

**Tasks**

- [ ] Display pricing for events using the provided rate information.
- [ ] Clearly display student discount information with the pricing for events.
